export const FIND_RESTAURANTS_LOADING = 'FIND_RESTAURANTS_LOADING';
export const FIND_RESTAURANTS_SUCCESS = 'FIND_RESTAURANTS_SUCCESS';
export const FIND_RESTAURANTS_ERROR = 'FIND_RESTAURANTS_ERROR';
