//searching restaurant types
export const FIND_RESTAURANTS_LOADING = 'FIND_RESTAURANTS_LOADING';
export const FIND_RESTAURANTS_SUCCESS = 'FIND_RESTAURANTS_SUCCESS';
export const FIND_RESTAURANTS_ERROR = 'FIND_RESTAURANTS_ERROR';

export const RANDOM_RESTAURANT_LOADING = 'RANDOM_RESTAURANT_LOADING';
export const RANDOM_RESTAURANT_SUCCESS = 'RANDOM_RESTAURANT_SUCCESS';
export const RANDOM_RESTAURANT_ERROR = 'RANDOM_RESTAURANT_ERROR';

export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';
export const CLEAR_SEARCH_RESUTLS = 'CLEAR_SEARCH_RESUTLS';

//interaction
export const TOGGLE_SEARCHING = 'TOGGLE_SEARCHING';
